[build]
  publish = "out"
  command = "node scripts/generate-sitemap.mjs && pnpm run build"

  environment = { NODE_VERSION = "20.18.2", NPM_FLAGS = "--legacy-peer-deps" }

[[plugins]]
  package = "@netlify/plugin-nextjs"
