[build]
  publish = "out"
  command = "node scripts/generate-sitemap.mjs && npm run build && npx next export"

  environment = { NODE_VERSION = "20.18.2", NPM_FLAGS = "--legacy-peer-deps", NETLIFY_NEXT_PLUGIN_SKIP = "true" }

[[plugins]]
  package = "@netlify/plugin-nextjs"
