[build]
  publish = "out"
  command = "node scripts/generate-sitemap.mjs && pnpm run build && pnpm run export"

  environment = { NODE_VERSION = "20.18.2", NETLIFY_NEXT_PLUGIN_SKIP = "true" }

[[plugins]]
  package = "@netlify/plugin-nextjs"
